name: Release Packages

on:
 push:
   tags:
     - 'v[0-9]+.[0-9]+.[0-9]+'

# Needed to create release and upload assets
permissions:
  contents: write

jobs:
  build-deb:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: registry-1.docker.io/dashinfer/dev-ubuntu-22.04-x86:v1
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
        
    - name: Pull LFS
      run: |
        git lfs pull
        
    - name: Build deb package
      run: |
        git fetch --tags
        TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
        VERSION_NUMBER=$(echo "$TAG_NAME" | sed 's/^v//')
        source activate ds_py
        AS_RELEASE_VERSION=$VERSION_NUMBER \
        AS_PLATFORM="x86" \
        AS_BUILD_PACKAGE=ON \
        bash build.sh
        
    - name: Upload deb package
      uses: actions/upload-artifact@v3
      with:
        name: dashinfer-deb
        path: build/*.deb

  build-rpm:
    strategy:
      matrix:
        arch: [X64, ARM64]
        image: ["dev-centos7-x86:v1", "dev-alinux-arm:v1"]
        exclude:
          - arch: X64
            image: "dev-alinux-arm:v1"
          - arch: ARM64
            image: "dev-centos7-x86:v1"
    runs-on: [self-hosted, Linux, "${{ matrix.arch }}"]
    container:
      image: registry-1.docker.io/dashinfer/${{ matrix.image }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Pull LFS
      run: |
        git lfs pull
        
    - name: Build rpm package
      run: |
        git fetch --tags
        TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
        VERSION_NUMBER=$(echo "$TAG_NAME" | sed 's/^v//')
        source /opt/rh/devtoolset-7/enable
        source activate ds_py
        AS_RELEASE_VERSION=$VERSION_NUMBER \
        AS_PLATFORM=[[ "${{ matrix.arch }}" = "X64" ]] && "x86" || "armclang" \
        AS_BUILD_PACKAGE=ON \
        bash build.sh
  
    - name: Upload rpm package
      uses: actions/upload-artifact@v3
      with:
        name: dashinfer-rpm-${{ matrix.arch }}
        path: build/*.rpm
      

  build-wheels:
    strategy:
      matrix:
        arch: [X64, ARM64]
        image: ["dev-manylinux-x86:v1", "dev-manylinux-arm:v1"]
        exclude:
          - arch: X64
            image: "dev-manylinux-arm:v1"
          - arch: ARM64
            image: "dev-manylinux-x86:v1"
    runs-on: [self-hosted, Linux, "${{ matrix.arch }}"]
    container:
      image: registry-1.docker.io/dashinfer/${{ matrix.image }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      env:
        # force use node16 instead of node20
        # otherwise it may cause GLIBCXX_2.27 not found
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      with:
        lfs: true
        
    - name: Build manylinux wheels
      run: |
        git fetch --tags
        TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
        VERSION_NUMBER=$(echo "$TAG_NAME" | sed 's/^v//')
        AS_RELEASE_VERSION=$VERSION_NUMBER bash scripts/release/python_manylinux_build.sh

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: python-manylinux-wheels-${{ matrix.arch }}
        path: python/wheelhouse/*-manylinux*.whl
        
  test:
    strategy:
      matrix:
        arch: [X64, ARM64]
        image: ["test-ubuntu-x86:v1", "test-centos-arm:v1"]
        exclude:
          - arch: X64
            image: "test-centos-arm:v1"
          - arch: ARM64
            image: "test-ubuntu-x86:v1"
    runs-on: [self-hosted, Linux, "${{ matrix.arch }}"]
    container:
      image: registry-1.docker.io/dashinfer/${{ matrix.image }}
      volumes:
        - /mnt/data0/models/modelscope:/github/home/.cache/modelscope
      options: "--ipc=host --cap-add SYS_NICE --cap-add SYS_PTRACE"
    needs: build-wheels
    steps:
    - name: Check out code
      uses: actions/checkout@v3
        
    - name: Download wheels
      uses: actions/download-artifact@v3
      with:
        name: python-manylinux-wheels-${{ matrix.arch }}
        path: python/wheelhouse
        
    - name: Test manylinux wheels
      run: |
        TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
        VERSION_NUMBER=$(echo "$TAG_NAME" | sed 's/^v//')
        AS_RELEASE_VERSION=$VERSION_NUMBER bash scripts/release/python_manylinux_test.sh

  publish:
    runs-on: [self-hosted, Linux]
    needs: [build-deb, build-rpm, test]
    strategy:
      matrix:
        arch: [X64, ARM64]
    steps:
    - name: Download deb packages
      uses: actions/download-artifact@v3
      with:
        name: dashinfer-deb
        path: release/
      
    - name: Download rpm packages
      uses: actions/download-artifact@v3
      with:
        name: dashinfer-rpm-${{ matrix.arch }}
        path: release/

    - name: Download python wheels
      uses: actions/download-artifact@v3
      with:
        name: python-manylinux-wheels-${{ matrix.arch }}
        path: release/

    - name: Release all packages
      uses: softprops/action-gh-release@v2
      with:
        files: release/*
    

    
